package updater

import (
	"archive/zip"
	"bytes"
	"path/filepath"
	"strings"
	"testing"
)

type entry struct{ name, body string }

func zipBytes(t *testing.T, entries ...entry) *zip.Reader {
	t.Helper()
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	for _, e := range entries {
		f, err := w.Create(e.name)
		if err != nil {
			t.Fatal(err)
		}
		f.Write([]byte(e.body))
	}
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}
	r, err := zip.NewReader(bytes.NewReader(buf.Bytes()), int64(buf.Len()))
	if err != nil {
		t.Fatal(err)
	}
	return r
}

const testManifest = "Manifest-Version: 1.0\r\nImplementation-Title: FabricInstaller\r\nImplementation-Version: 1.1.2\r\nMain-Class: net.fabricmc.installer.ServerLauncher\r\n\r\n"

var installerEntries = []entry{{"META-INF/MANIFEST.MF", testManifest}, {"net/", ""}, {"net/fabricmc/A.class", "class bytes"}}

func launcherEntries(props string, extra ...entry) []entry {
	return append(append(append([]entry{}, installerEntries...), entry{"install.properties", props}), extra...)
}

var want = fabricLauncherInfo{Installer: "1.1.2", Loader: "0.19.5", Minecraft: "1.21.10"}

const goodProps = "fabric-loader-version=0.19.5\ngame-version=1.21.10"

func TestInspectFabricLauncher(t *testing.T) {
	got, err := inspectFabricLauncher(zipBytes(t, launcherEntries(goodProps)...))
	if err != nil || got != want {
		t.Fatalf("got %+v, %v", got, err)
	}
	if _, err := inspectFabricLauncher(zipBytes(t, installerEntries...)); err != errNotFabricLauncher {
		t.Fatalf("installer without install.properties: %v", err)
	}
	vanilla := zipBytes(t, entry{"META-INF/MANIFEST.MF", "Main-Class: net.minecraft.bundler.Main\n"}, entry{"install.properties", goodProps})
	if _, err := inspectFabricLauncher(vanilla); err != errNotFabricLauncher {
		t.Fatalf("vanilla manifest: %v", err)
	}
}

func TestVerifyFabricLauncher(t *testing.T) {
	inst := zipBytes(t, installerEntries...)
	if err := verifyFabricLauncher(zipBytes(t, launcherEntries(goodProps)...), inst, want); err != nil {
		t.Fatalf("genuine launcher rejected: %v", err)
	}
	bad := map[string]*zip.Reader{
		"extra entry":     zipBytes(t, launcherEntries(goodProps, entry{"evil/Payload.class", "x"})...),
		"modified entry":  zipBytes(t, entry{"META-INF/MANIFEST.MF", testManifest}, entry{"net/", ""}, entry{"net/fabricmc/A.class", "tampered"}, entry{"install.properties", goodProps}),
		"missing entry":   zipBytes(t, entry{"META-INF/MANIFEST.MF", testManifest}, entry{"install.properties", goodProps}),
		"wrong loader":    zipBytes(t, launcherEntries("fabric-loader-version=0.18.1\ngame-version=1.21.10")...),
		"wrong game":      zipBytes(t, launcherEntries("fabric-loader-version=0.19.5\ngame-version=1.21.9")...),
		"extra key":       zipBytes(t, launcherEntries(goodProps+"\nmain-class=evil.Main")...),
		"duplicate props": zipBytes(t, launcherEntries(goodProps, entry{"install.properties", goodProps})...),
		"duplicate entry": zipBytes(t, launcherEntries(goodProps, entry{"net/fabricmc/A.class", "class bytes"})...),
	}
	for name, launcher := range bad {
		if err := verifyFabricLauncher(launcher, inst, want); err == nil {
			t.Errorf("%s: accepted", name)
		}
	}
	if err := verifyFabricLauncher(zipBytes(t, launcherEntries(goodProps)...), inst, fabricLauncherInfo{Installer: "1.1.1", Loader: "0.19.5", Minecraft: "1.21.10"}); err == nil || !strings.Contains(err.Error(), "1.1.1") {
		t.Errorf("installer version mismatch accepted or unexplained: %v", err)
	}
}

func openTestZip(t *testing.T, name string) *zip.Reader {
	t.Helper()
	r, err := zip.OpenReader(filepath.Join("testdata", "fabric", name))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { r.Close() })
	return &r.Reader
}

// The real launcher is a production server.jar generated by meta.fabricmc.net;
// the installer is fabric-installer-1.1.0-server.jar from maven.fabricmc.net
// (sha1 6d22df8cb75c87317965b0893caf7f413ad3c8bb).
func TestVerifyRealFabricLauncher(t *testing.T) {
	launcher := openTestZip(t, "launcher-1.1.0-0.18.1-1.21.10.jar")
	installer := openTestZip(t, "fabric-installer-1.1.0-server.jar")
	info := fabricLauncherInfo{Installer: "1.1.0", Loader: "0.18.1", Minecraft: "1.21.10"}
	if got, err := inspectFabricLauncher(launcher); err != nil || got != info {
		t.Fatalf("inspect: %+v, %v", got, err)
	}
	if err := verifyFabricLauncher(launcher, installer, info); err != nil {
		t.Fatalf("genuine launcher rejected: %v", err)
	}
	if _, err := inspectFabricLauncher(installer); err != errNotFabricLauncher {
		t.Fatalf("installer without install.properties identified as launcher: %v", err)
	}
}
